DB_URL=jdbc:h2:mem:coretaf;DB_CLOSE_DELAY=-1
#jdbc:sqlserver://localhost:1433;databaseName=GoBus;encrypt=true;trustServerCertificate=true
DB_USERNAME=sa
DB_PASSWORD=
DB_DRIVER=org.h2.Driver
#com.microsoft.sqlserver.jdbc.SQLServerDriver